spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/demoRestfulService
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/main-changelog.xml